## Spring Boot application configuration file
---
spring:
    data:
        rest:
            detection-strategy: annotated
            base-path: /api
            default-page-size: 20
            max-page-size: 50
            page-param-name: p
            limit-param-name: l
            sort-param-name: s
            return-body-on-create: true
            return-body-on-update: false
    h2:
        console:
            enabled: true
    datasource:
        platform: h2
        url: jdbc:h2:mem:DEV_DB
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    batch_size: 50
                validator:
                    apply_to_ddl: false
keycache:
    secret-key-key-store:
        resource: file:src/main/resources/key-store.ks
        password-resource: file:src/main/resources/key-store.password
        key-store-type: JCEKS
        key-passwords:
            sample-key-v1: file:src/main/resources/sample-key-v1.password
crypto:
    key-dictionary:
        key-codes:
            sample-key: 1
cryptonate:
    encryption-key-name: sample-key
    rng-additional-data: Cryptonate Spring Boot Example
